- src/main/kotlin/com/itangcent/common/utils/FileUtils.kt
- src/main/kotlin/com/itangcent/intellij/actions/ActionEventDataContextAdaptor.kt
- src/main/kotlin/com/itangcent/intellij/actions/KotlinAnAction.kt
- src/main/kotlin/com/itangcent/intellij/config/PathSearchConfigReader.kt
- src/main/kotlin/com/itangcent/intellij/config/rule/RuleKit.kt
- src/main/kotlin/com/itangcent/intellij/config/rule/SimpleRuleKey.kt
- src/main/kotlin/com/itangcent/intellij/context/ActionContext.kt
- src/main/kotlin/com/itangcent/intellij/extend/guice/KotlinModule.kt
- src/main/kotlin/com/itangcent/intellij/file/AbstractLocalFileRepository.kt
- src/main/kotlin/com/itangcent/intellij/file/DefaultLocalFileRepository.kt
- src/main/kotlin/com/itangcent/intellij/logger/DefaultNotificationHelper.kt
- src/main/kotlin/com/itangcent/intellij/logger/NotificationHelper.kt
- src/main/kotlin/com/itangcent/intellij/psi/DuckTypeHelper.kt
- src/main/kotlin/com/itangcent/intellij/psi/PsiClassUtils.kt
- src/main/kotlin/com/itangcent/intellij/psi/SourceHelper.kt
- src/main/kotlin/com/itangcent/intellij/util/ActionUtils.kt
1. support bind Class in KotlinModule
2. opti: fix RuleKit
3. use File.separator instead of "/"
> chore: some update

- commons/src/main/kotlin/com/itangcent/common/utils/KV.kt
- commons/src/main/kotlin/com/itangcent/common/utils/MapKit.kt
- commons/src/main/kotlin/com/itangcent/common/utils/Streams.kt
- guice-action/src/main/kotlin/com/itangcent/intellij/extend/guice/Injectors.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/AbstractPsiClassHelper.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/DefaultPsiClassHelper.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/DuckType.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/AbstractLinkResolve.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/ArrayDuckType.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/DuckType.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/DuckTypeHelper.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/JvmClassHelper.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/LinkExtractor.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/LinkResolver.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/PsiClassHelper.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/PsiResolver.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/SingleDuckType.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardLinkExtractor.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolver.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/FqNameHelper.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KotlinAnnotationHelper.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KotlinAutoInject.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KotlinDocHelper.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KotlinLinkExtractor.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KotlinPsiResolver.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KtPsiUtils.kt
- support kotlin [annotation](https://kotlinlang.org/docs/reference/annotations.html)
- support kotlin [doc link](https://kotlinlang.org/docs/reference/kotlin-doc.html)
> resolve kotlin @annotation&[doc link]

- commons/src/main/kotlin/com/itangcent/common/utils/Streams.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/AbstractConfigReader.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardAnnotationHelper.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolver.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KotlinAnnotationHelper.kt
> opti: read kdoc

- commons/src/main/kotlin/com/itangcent/common/utils/Streams.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/BooleanRule.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/DefaultRuleComputer.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/DefaultRuleLookUp.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/PsiFieldContext.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/PsiMethodContext.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/PsiTypeContext.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/Rule.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/RuleComputer.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/RuleContext.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/RuleKit.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/RuleParser.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/SimpleRuleParser.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/StringRule.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/StringRuleContext.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/UnknownPsiElementContext.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/AbstractPsiClassHelper.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/ClassRuleKeys.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/DefaultPsiClassHelper.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/PsiClassUtils.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/JvmClassHelper.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/PsiResolver.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardJvmClassHelper.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolver.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KotlinPsiResolver.kt
by default resolve enum as it's name `String`
> by default resolve enum as it's name `String`

- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/AbstractClassRuleConfig.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/DefaultClassRuleConfig.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/DefaultPsiClassHelper.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/util/MapKit.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/DuckTypeHelper.kt
optimized:DefaultClassRuleConfig support
> optimized:DefaultClassRuleConfig support

- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardAnnotationHelper.kt
fix https://github.com/tangcent/easy-yapi/issues/165
> fix resolve expression for annotation

- .gitignore
- build.gradle
- commons/build.gradle
- guice-action/build.gradle
- intellij-idea/build.gradle
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/AbstractConfigReader.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/AbstractPsiClassHelper.kt
- intellij-jvm/build.gradle
- intellij-kotlin-support/build.gradle
- intellij-scala-support/build.gradle
- script/publish.gradle
chore: polish AbstractPsiClassHelper#copy
feat: catch yaml parse error.
> chore: set version 0.7.2-SNAPSHOT

- build.gradle
- commons/build.gradle
- commons/src/main/kotlin/com/itangcent/common/utils/ReflectKit.kt
- guice-action/build.gradle
- intellij-idea/build.gradle
- intellij-jvm/build.gradle
- intellij-kotlin-support/build.gradle
- intellij-scala-support/build.gradle
- intellij-scala-support/src/main/kotlin/com/itangcent/intellij/jvm/scala/ScalaDocHelper.kt
- intellij-scala-support/src/main/kotlin/com/itangcent/intellij/jvm/scala/adaptor/ScDocTagAdaptor.kt
> chore: set version 0.7.3-SNAPSHOT

- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/AbstractConfigReader.kt
fix path bug under windows  @[https://github.com/tangcent/easy-yapi/issues/215](https://github.com/tangcent/easy-yapi/issues/215)
> fix: resolve file path in windows

- commons/src/main/kotlin/com/itangcent/common/threadpool/eager/EagerThreadPoolExecutor.kt
- commons/src/main/kotlin/com/itangcent/common/utils/ThreadPoolUtils.kt
Refactor from https://github.com/apache/dubbo/tree/master/dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/eager
> feat: use EagerThreadPoolExecutor instead of  ThreadPoolExecutor

- build.gradle
- commons/build.gradle
- guice-action/build.gradle
- intellij-idea/build.gradle
- intellij-jvm/build.gradle
- intellij-kotlin-support/build.gradle
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KotlinAnnotationHelper.kt
- intellij-scala-support/build.gradle
KtCallExpression/KtValueArgumentList/KtValueArgument/KtValueArgumentName
> fix: resolve several kt expressions

- build.gradle
- commons/build.gradle
- commons/src/main/kotlin/com/itangcent/common/utils/AnyKit.kt
- commons/src/main/kotlin/com/itangcent/common/utils/ReflectKit.kt
- commons/src/main/kotlin/com/itangcent/common/utils/StringKit.kt
- guice-action/build.gradle
- intellij-idea/build.gradle
- intellij-idea/src/main/kotlin/com/itangcent/intellij/adaptor/ModuleAdaptor.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/PathSearchConfigReader.kt
- intellij-jvm/build.gradle
- intellij-kotlin-support/build.gradle
- intellij-scala-support/build.gradle
- intellij-scala-support/src/main/kotlin/com/itangcent/intellij/jvm/scala/adaptor/ScTypeArgsAdaptor.kt
- intellij-scala-support/src/main/kotlin/com/itangcent/intellij/jvm/scala/adaptor/ScalaPsiParameterAdaptor.kt
> fix:fix compatibility problems for IntelliJ IDEA Ultimate IU-203.3645

- build.gradle
- commons/build.gradle
- guice-action/build.gradle
- intellij-idea/build.gradle
- intellij-jvm/build.gradle
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiExpressionResolver.kt
- intellij-kotlin-support/build.gradle
- intellij-scala-support/build.gradle
> opti: StandardPsiExpressionResolver#registerExpressionResolver

- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/PsiResolver.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolver.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KotlinPsiResolver.kt
- intellij-scala-support/src/main/kotlin/com/itangcent/intellij/jvm/scala/ScalaPsiResolver.kt
> opti: resolve inner class

- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/AbstractPsiClassHelper.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/DuckTypeHelper.kt
> feat: resolve PsiWildcardType

- build.gradle
- commons/build.gradle
- guice-action/build.gradle
- intellij-idea/build.gradle
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/AbstractPsiClassHelper.kt
- intellij-jvm/build.gradle
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/PsiClassHelper.kt
- intellij-kotlin-support/build.gradle
- intellij-scala-support/build.gradle
> opti: Delay compute the parse result

- build.gradle
- commons/build.gradle
- guice-action/build.gradle
- guice-action/src/main/kotlin/com/itangcent/intellij/logger/LogConsoleRunner.kt
- intellij-idea/build.gradle
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/DefaultClassRuleConfig.kt
- intellij-jvm/build.gradle
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/DuckTypeHelper.kt
- intellij-kotlin-support/build.gradle
- intellij-scala-support/build.gradle
use `com.intellij.psi.PsiImportStatementBase#isOnDemand` instead of ` it.qualifiedName.endsWith(".*")`
---
fix tangcent/easy-yapi#322
> fix: resolve on-demand import

- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/DuckTypeHelper.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardAnnotationHelper.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardDocHelper.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolver.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KotlinPsiResolver.kt
- intellij-scala-support/src/main/kotlin/com/itangcent/intellij/jvm/scala/ScalaPsiResolver.kt
* default-imports for kotlin: https://kotlinlang.org/docs/reference/packages.html#default-imports
* default-imports for scala: https://www.scala-lang.org/files/archive/spec/2.13/09-top-level-definitions.html
> opti: import default packages for `kotlin`&`scala`

- build.gradle
- commons/build.gradle
- commons/src/main/kotlin/com/itangcent/common/utils/FileUtils.kt
- commons/src/main/kotlin/com/itangcent/common/utils/HttpsKit.kt
- commons/src/main/kotlin/com/itangcent/common/utils/IOKit.kt
- guice-action/build.gradle
- intellij-idea/build.gradle
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/AbstractConfigReader.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/resource/DefaultResourceResolver.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/resource/FileResource.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/resource/Resource.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/resource/ResourceResolver.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/resource/URLResource.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/file/AbstractLocalFileRepository.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/file/CachedBeanBinder.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/file/DefaultLocalFileRepository.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/util/ActionUtils.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/util/FileUtils.kt
- intellij-jvm/build.gradle
- intellij-kotlin-support/build.gradle
- intellij-scala-support/build.gradle
`properties.additional` support url like:
```
properties.additional=https://raw.githubusercontent.com/tangcent/easy-yapi/master/idea-plugin/src/main/resources/.recommend.easy.api.config
```
> opti: `properties.additional` support url

- commons/src/main/kotlin/com/itangcent/common/utils/AnyKit.kt
- commons/src/main/kotlin/com/itangcent/common/utils/GsonUtils.kt
- commons/src/main/kotlin/com/itangcent/common/utils/SimpleExtensible.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/AbstractPsiClassHelper.kt
> fix: remove usage of `AbstractPsiClassHelper#copy`

- intellij-idea/src/test/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolverTest.kt
- intellij-idea/src/test/resources/cases/LinkCase.java
- intellij-idea/src/test/resources/cases/NestedClass.java
- intellij-idea/src/test/resources/cases/NestedClassB.java
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/DuckTypeHelper.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/JvmClassHelper.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/PsiResolver.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolver.kt
test case: [intellij-idea/src/test/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolverTest.kt](https://github.com/tangcent/intellij-kotlin/blob/b48c9a506b651e19f0f33ef3f7f467443ad42ce9/intellij-idea/src/test/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolverTest.kt)
> fix: resolve on-demand imports

- intellij-idea/src/test/kotlin/com/itangcent/intellij/jvm/standard/StandardEnumFieldResolverTest.kt
- intellij-idea/src/test/resources/constant/MyConstant.java
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/PsiUtils.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardEnumFieldResolver.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolver.kt
> feat: resolve enum fields with construct

- intellij-idea/src/main/kotlin/com/itangcent/intellij/constant/RuleConstant.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/AbstractPsiClassHelper.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/DefaultClassRuleConfig.kt
max.deep -> 10
max.elements -> 512
> feat: update default rule

- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/PsiResolver.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/element/ExplicitMethod.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolver.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KotlinPsiResolver.kt
> feat: resolve suspend function in kotlin

- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/AbstractPsiClassHelper.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/ClassRuleKeys.kt
> feat: new rule `enum.use.custom`

- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/AbstractPsiClassHelper.kt
- intellij-idea/src/test/kotlin/com/itangcent/intellij/jvm/DuckTypeHelperTest.kt
- intellij-idea/src/test/kotlin/com/itangcent/intellij/psi/DefaultPsiClassHelperTest.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/element/ExplicitClass.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/element/ExplicitMethod.kt
> feat: adjust the order in collect fields/methods

- commons/src/main/kotlin/com/itangcent/common/utils/StringKit.kt
- commons/src/test/kotlin/com/itangcent/common/utils/StringKitTest.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/adapt/Property.kt
- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolver.kt
> feat: resolve import from outer class

- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/SelectedHelper.kt
- intellij-idea/src/test/kotlin/com/itangcent/intellij/extend/rx/ThrottleHelperKtTest.kt
> feat: reorder traversal logic to prioritize navigatables

- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/feature/RecordDocHelper.kt
> feat: Parse the document from @param on the record class

- commons/src/main/kotlin/com/itangcent/common/utils/StringKit.kt
- commons/src/test/kotlin/com/itangcent/common/utils/StringKitTest.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/AbstractPsiClassHelper.kt
- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/PsiClassUtils.kt
> fix: Resolve NPE in AbstractPsiClassHelper.getResolveContext

- intellij-groovy-support/src/main/kotlin/com/itangcent/intellij/jvm/groovy/GrDocHelper.kt
- intellij-groovy-support/src/main/kotlin/com/itangcent/intellij/jvm/groovy/GrPsiExpressionResolver.kt
- intellij-groovy-support/src/main/kotlin/com/itangcent/intellij/jvm/groovy/GrPsiUtils.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KotlinDocHelper.kt
- intellij-kotlin-support/src/main/kotlin/com/itangcent/intellij/jvm/kotlin/KtPsiUtils.kt
> fix: Fix issue with discarding field documentation when configuring 'field.doc' rule

- intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolver.kt
> fix: The resolveReferenceFromImport method no longer discards generic types

- intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/SelectedHelper.kt
fix tangcent/easy-yapi#1080 
fix tangcent/easy-yapi#1050
> fix: Resolve SelectedHelper not functioning correctly in multiple scenarios

- intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/DefaultRuleLookUp.kt
> fix: fix NullPointerException in `lookUp` method
